[package]
name = "kcli"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
prettytable-rs = "0.10.0"
rdkafka = { version = "0.36.2", features = ["cmake-build", "zstd"] }
serde = { version = "1.0.210", features = ["derive"] }

toml = "0.8.19"
